spring.application.name=TRBL_Individual_API

#Conexao DB

spring.datasource.url=jdbc:postgresql://localhost:5433/TRBL-API
spring.datasource.username=postgres
spring.datasource.password=0240

#DDL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true